http:
  middlewares:
    oauth2-proxy-auth:
      forwardAuth:
        address: http://oauth2-proxy:4180/oauth2/auth
        authResponseHeaders:
          - Authorization
          - X-Auth-Request-Email
          - X-Auth-Request-User
        trustForwardHeader: true
        authURL: http://10.216.68.222:8088/oauth2/start