
FROM rust:1.88.0-alpine AS build

WORKDIR /app


RUN apk add --no-cache clang lld musl-dev git


COPY Cargo.toml Cargo.lock ./


RUN mkdir src && echo "fn main() {}" > src/main.rs && \
    cargo build --release --target x86_64-unknown-linux-musl && \
    rm -rf src


COPY src ./src


COPY templates ./templates


RUN cargo build --release && \
    cp ./target/release/display-food /bin/server



FROM alpine:3.18 AS final


ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
USER appuser


COPY --from=build /bin/server /bin/


COPY --from=build /app/templates /templates


EXPOSE 3001

CMD ["/bin/server"]