name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push food-list service
        uses: docker/build-push-action@v5
        with:
          context: ./food-post-service
          file: ./food-post-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/food-list:latest

      - name: Build and push post-list service
        uses: docker/build-push-action@v5
        with:
          context: ./display-post-service
          file: ./display-post-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/display-post:latest

      - name: Build and push todo-list service
        uses: docker/build-push-action@v5
        with:
          context: ./display-todo-service
          file: ./display-todo-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/display-todo:latest
