name: automated package push for backend

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: todo-service 
  IMAGE_PATH: mbiti2

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        uses: docker/build-push-action@v4
        with:
          context: ./display-todos-service
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_PATH }}/${{ env.IMAGE_NAME }}:latest